dragonmantank/cron-expression

- src/Cron/DayOfWeekField.php
- tests/Cron/DayOfWeekFieldTest.php
Using L to find the last given weekday of a month passes validation but fails on resolving the next run date if weekday literals are used. E.g expression `* * * * FRIL` is considered valid but will fail because of an infinite loop.
This is regression caused by changes to literal conversion. Current implementation checks for whole matches and weekday ending with L will not be converted while the old implementation replaced matching substrings with numbers regardless. As a result, the `isSatisfiedBy` method ends up in an infinite loop trying to find a date where "FRI" is equal to an integer representation of a weekday which never happens.
Proposed change reruns literal conversion on a substring without L once it is clear that last weekday of the month check will be done.
> Fixed infinite loop when resolving last weekday of the month from literals

- .travis.yml
- composer.json
* Use SemVer to only allow releases from PHP 7.x branches;
* Add support for `phpunit/phpunit: ^7.0`;
* Add CI support to execute tests with PHP `7.2` and PHP `nightly`, removing `hhvm`;
* Add tests for all supported PHP versions with lowest dependencies;
* Use own `phpunit/phpunit` dev dependency instead of relying on the Travis built in version;
* Add "extra.branch-alias" at `composer.json` in order to allow installs for dev versions while respecting SemVer.
> [dependencies] Improve dependency declaration

- src/Cron/CronExpression.php
In the [CronExpression::determineTimeZone](https://github.com/dragonmantank/cron-expression/blob/v2.2.0/src/Cron/CronExpression.php#L399) method don't check for concrete class of `DateTime` but allow also `DateTimeImmutable` by evaluating for instance of  `DateTimeInterface`.
reference: [php.net: DateTimeInterface](http://php.net/manual/en/class.datetimeinterface.php)
> Get timezone from DateTimeInterface

- src/Cron/CronExpression.php
- src/Cron/DayOfMonthField.php
- src/Cron/DayOfWeekField.php
- src/Cron/FieldInterface.php
- src/Cron/HoursField.php
- src/Cron/MinutesField.php
- src/Cron/MonthField.php
- tests/Cron/CronExpressionTest.php
- tests/Cron/DayOfMonthFieldTest.php
- tests/Cron/DayOfWeekFieldTest.php
- tests/Cron/HoursFieldTest.php
- tests/Cron/MinutesFieldTest.php
- tests/Cron/MonthFieldTest.php
Allow `DateTimeImmutable` to be passed as arguments wherever `DateTime` is currently allowed. Logical continuation of #26
> Support DateTimeImmutable

- composer.json
[PHPStan](https://github.com/phpstan/phpstan) be invoked with `composer phpstan` which will run at (the default) "rule level 0". Might be good to try to increase this 🤓
Following results for the rule levels:
0. currently no errors
1. 1 error in a test
1. 3 errors
1. 3 errors
1. 6 errors
1. 26 errors
1. 42 errors
1. 48 errors
> Introduce PHPStan

- src/Cron/AbstractField.php
- tests/Cron/HoursFieldTest.php
- tests/Cron/MinutesFieldTest.php
- tests/Cron/MonthFieldTest.php
This evaluates numeric field ranges as invalid.
For example to create expression that is run in 10 minute interval with 1 minute offset:
- Invalid: `1/10 * * * *`
- Valid: `1-59/10 * * * *`
ATM expression above is evaluated to be due only once per hour (hh:01)
Fixes #44
> Handle invalid numeric ranges

- src/Cron/CronExpression.php
When using the `CronExpression` constructor, passing `null` for `$fieldFactory` will result in an unusable object as the fieldFactory is required. This pull request fixes this issue.
But I'd like to ask one question: why do we have a `factory()` method? I don't see the need as everything could be done in the constructor instead. Having 2 ways of creating a `CronExpression` also means that you cannot use shortcuts such as `@daily` when using the constructor. What about removing/deprecating the `factory()` method and move the logic to the constructor instead?
> Fix constructor optional argument

- src/Cron/CronExpression.php
The current implementation of "dropping seconds" might lead to a timezone issue as the new date will have UTC. Instead of passing the timezone, I propose to use `setTime()` which seems more appropriate (and used elsewhere in the code base).
> Fix issue with timezones

- src/Cron/CronExpression.php
The `isDue()` method clones the given date except when it's a `DateTime` instance. As we are modifying the date, I think we should clone it.
> Fix cloning dates in isDue()

- tests/Cron/CronExpressionTest.php
- tests/Cron/DayOfWeekFieldTest.php
- tests/Cron/FieldFactoryTest.php
From PHPUnit 8:
> The @expectedException, @expectedExceptionCode,
> @expectedExceptionMessage, and @expectedExceptionMessageRegExp
> annotations are deprecated. They will be removed in PHPUnit 9.
> Refactor your test to use expectException(), expectExceptionCode(),
> expectExceptionMessage(), or expectExceptionMessageRegExp() instead.
This change is compatible with PHPUnit 6.4, the oldest version of currently supported according to the composer.json file.
> Replace deprecated expectedException annotations

- composer.json
Will avoid that both mtdowling/cron-expression and this package is installed parallel in a composer.json. So this will completely replace the old package.
> Mark this package as replace for mtdowling/cron-expression

- src/Cron/CronExpression.php
- tests/Cron/CronExpressionTest.php
This provides additional logic if both a Day of Month and a Day of Week value are supplied. Most cron implementations treat these two values as an OR problem, unlike the rest of the expression which is joined together via ANDs. For example:
`30 0 1 * 1`
should evaluate to "Run 30 minutes after the 0 hour on Day Of Month 1 OR a Monday", compared to the existing behavior of "Run 30 minutes after the 0 hour when the Day Of Month is 1 AND a Monday". 
This will widen the amount of days such an expression can trigger on, but is more in-line with existing implementations.
> Initial fix for and/or problem

- src/Cron/CronExpression.php
- src/Cron/FieldFactoryInterface.php
The constructor for CronExpression should take a FieldFactoryInterface,
not FieldFactory.
FieldFactoryInterface should return FieldInterface.
I'm aware this is similar to PR #86 but I think this one is more complete.
Would close #97  
Would close #86
> Allow proper usage of interfaces

- README.md
- src/Cron/CronExpression.php
- tests/Cron/CronExpressionTest.php
This would close #56 
If needed, we can specify a specific version in which the factory will be removed entirely.
> Depreceate CronExpression::factory and remove references

- phpunit.xml.dist
Phpunit had output warnings with the outdated configuration. This runs
--migrate-configuration to update it.
> Updates Phpunit configuration

- .travis.yml
- composer.json
- phpstan.neon
- src/Cron/AbstractField.php
- src/Cron/CronExpression.php
- src/Cron/DayOfMonthField.php
- src/Cron/DayOfWeekField.php
- src/Cron/FieldFactory.php
- src/Cron/FieldFactoryInterface.php
- src/Cron/FieldInterface.php
- src/Cron/HoursField.php
- src/Cron/MinutesField.php
- src/Cron/MonthField.php
- tests/Cron/CronExpressionTest.php
- tests/Cron/DayOfMonthFieldTest.php
- tests/Cron/DayOfWeekFieldTest.php
- tests/Cron/FieldFactoryTest.php
- tests/Cron/HoursFieldTest.php
- tests/Cron/MinutesFieldTest.php
- tests/Cron/MonthFieldTest.php
Hello,
I do: 
* Set PHPStan to level max (ie 8) https://phpstan.org/user-guide/rule-levels.
* Fix issues throws by PHPStan
* Add PHPStan to Travis
It improve DX :rocket:
> set phpstan to level max and fix issues

- .github/workflows/tests.yml
- .travis.yml
- composer.json
- phpstan.neon
- src/Cron/AbstractField.php
- src/Cron/CronExpression.php
- src/Cron/DayOfMonthField.php
- src/Cron/DayOfWeekField.php
- src/Cron/FieldFactory.php
- src/Cron/FieldInterface.php
- src/Cron/HoursField.php
- src/Cron/MinutesField.php
- src/Cron/MonthField.php
- tests/Cron/CronExpressionTest.php
- tests/Cron/DayOfMonthFieldTest.php
- tests/Cron/DayOfWeekFieldTest.php
- tests/Cron/FieldFactoryTest.php
- tests/Cron/HoursFieldTest.php
- tests/Cron/MinutesFieldTest.php
- tests/Cron/MonthFieldTest.php
This should allow `phpstan` to fail while still validating the build from the unit tests.
> Added continue-on-failure to phpstan

- src/Cron/CronExpression.php
Hi, it seems to me here [CronExpression@getMultipleRunDates](https://github.com/dragonmantank/cron-expression/blob/master/src/Cron/CronExpression.php#L243) we can speed up the results. From the last received date, calculate the next one without using `$nth`.
```
public function testPerformance(): void
{
$start = microtime(true);
for ($i = 0; $i < 10; $i++) {
$cron = CronExpression::factory('*/2 * * * *');
$cron->getMultipleRunDates(200, 'now', false, true);
}
$this->assertTrue(true);
// Before: ~1.3. After: ~0.025
die(microtime(true) - $start);
}
```
For verification, I added the changes to the new method and checked this way:
```
public function testCompare(): void
{
$cron = CronExpression::factory('* * * * *');
$this->assertEquals(
$cron->getMultipleRunDates(50, '2008-11-09 00:05:00', …
```
> refactor(optimize): getMultipleRunDates method

- tests/Cron/FieldFactoryTest.php
- Using the `assertInstanceOf` to assert expected instance is same as result.
> Improve instance of assertion

- README.md
- src/Cron/CronExpression.php
- tests/Cron/CronExpressionTest.php
@see https://manpages.debian.org/buster/cron/crontab.5.en.html
this adds the `@midnight` to the mapping which is the same as `@daily`.
But since it is available in some cron implementations it should not be
indicated as invalid.
Signed-off-by: BlackEagle <ike.devolder@gmail.com>
> midnight is also an allowed shortcut in crontab

- src/Cron/AbstractField.php
- tests/Cron/AbstractFieldTest.php
Thanks to everyone who contributed to this amazing library.
This is my first pull request to an open source project, and I'm ready to learn, open to any comments :)
I had trouble with this library to run cron expressions like `*/3,1,1-12`, `1-30/2,31-59/5 * * * *`.
I found that, according to the assertions in the unit tests, this project regards cron expressions invalid when multiple ranges _and_ step are mixed. However, those expressions seem valid and also pass many online validators.
I switched the handling order of `/` and `,` characters in `\Cron\AbstractField::validate()` method to meet the semantic order of cron expression, and the library now works as expected.
After the code change, existing unit tests that invalidates such expressions now fails.
- …
> Fix "," delimiter precedence

- src/Cron/CronExpression.php
- tests/Cron/CronExpressionTest.php
In `\Cron\CronExpression::getRunDate` method, cron expressions with both day-of-month and day-of-week set are detected with special `if (isset($parts[2]) && isset($parts[4]))` check, and treated differently than other patterns. In this execution branch, the expression is treated as two separate expressions with wildcards instead of one of the dwo day parameters. The results are merged and sorted, and after that the corresponding `$nth` result is returned.
However, this method is used internally by both `getNextRunDate` and `getPreviousRunDate` methods of the class, and yet the sorting order is incorrectly the same in both cases, irrespective of the `$invert` parameter passed to the method.
This pull request fixes the bug and adds a test to prevent a future regression.
> Fix getPreviousRunDate return value for cron expression with both day-of-month and day-of-week set

- .github/workflows/tests.yml
- composer.json
- tests/Cron/CronExpressionTest.php
- Removing remote Docker image about `PHPStan`. Using the `composer phpstan` script instead.
- Adding `tests` folder to be analysed via customized `composer phpstan` script.
- Adding the returning `void` type hint to fix following PHPStan issue:
```Bash
peterli@peterli-Virtual-Machine:~/cron-expression$ php ~/composer.phar phpstan -n
For additional security you should declare the allow-plugins config with a list of packages names that are allowed to run code. See https://getcomposer.org/allow-plugins
You have until July 2022 to add the setting. Composer will then switch the default behavior to disallow all plugins.
> ./vendor/bin/phpstan analyse -l max src tests
Note: Using configuration file /home/peterli/cron-expression/phpstan.neon.
18/18 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
------ …
```
> Fix failing PHPStan issue

- src/Cron/CronExpression.php
- tests/Cron/CronExpressionTest.php
This PR is inspired by my work on [bakame/cron](https://github.com/bakame-php/cron-expression/releases/tag/0.5.0) to resolve #64 
here's the proposed public API:
```php
<?php
use Cron\CronExpression;
if (!CronExpression::supportsAlias('@every')) {
CronExpression::registerAlias('@every', '* * * * *');
}
CronExpression::getAliases();
// returns
// array (
//   '@yearly' => '0 0 1 1 *',
//   '@annually' => '0 0 1 1 *',
//   '@monthly' => '0 0 1 * *',
//   '@weekly' => '0 0 * * 0',
//   '@daily' => '0 0 * * *',
//   '@midnight' => '0 0 * * *',
//   '@hourly' => '0 * * * *',
//   '@every' => '* * * * *',
// )
CronExpression::supportsAlias('@foobar'); //return false
CronExpression::supportsAlias('@daily');  //return true
CronExpression::supportsAlias('@every');  //return true
$cron = new …
```
> Adding Registering alias feature to the package

- src/Cron/DayOfMonthField.php
PHP 8.2 deprecates `"${var}"` string interpolation pattern.
This fixes all three of such occurrences in `dragonmantank/cron-expression` package.
- [PHP 8.2: `${var}` string interpolation deprecated](https://php.watch/versions/8.2/${var}-string-interpolation-deprecated)
- [RFC](https://wiki.php.net/rfc/deprecate_dollar_brace_string_interpolation)
> [PHP 8.2] Fix `${var}` string interpolation deprecation

- tests/Cron/DaylightSavingsTest.php
As discussed in #133, the PHP 8.1's date extension daylight saving
APIs have been suffering with instabilities. Let's skip the affected
tests until https://github.com/php/php-src/issues/9165 is resolved.
Signed-off-by: Athos Ribeiro <athos.ribeiro@canonical.com>
> Skip PHP 8.1 unstable daylight savings tests

- src/Cron/CronExpression.php
- tests/Cron/CronExpressionTest.php
This solves #137 
Passing two question marks into a cron expression does not really make sense in my opinion, as you would neither specify the day of month nor the day of week. Wikipedia states
> In some implementations, used instead of '*' for leaving **either** day-of-month **or** day-of-week blank.
I guess, this is the implementation this library is following.
I've also added a check to validate if there are question marks in parts, where they are not allowed. 
Maybe there should be an extra step to validate each part against it's allowed values. What do you think about this?
> #137 Add check for multiple question marks

- src/Cron/MinutesField.php
Fix skipped next execution time
Minute parameters need to be sorted in order
> Fix skipped next execution time

- src/Cron/CronExpression.php
Added "throws" docblock section, so it's immediately obvious in which way an invalid cron expression will fail
> Add throws docblock in CronExpression constructor

- src/Cron/CronExpression.php
not doing this will be deprecated in PHP 8.4 (see e.g. https://github.com/symfony/symfony/actions/runs/8459191951/job/23175036483?pr=54426#step:8:508)
> explicitly mark nullable parameters as nullable

- .gitattributes
This duplicate was not added in alphabetical order and thus probably was missed during PR merge.
see 6dda2176a2e2092a2169bb7bab87046b8758165a
> Remove duplicate `/phpstan.neon` entry in .gitattributes

- composer.json
So that composer knows it can install dev-master when we want to test with the upcoming changes.
> Add branch-alias to composer.json

- .github/workflows/tests.yml
Add PHP 8.4 to test matrix.
No further changes should be needed, as the explicit nullable declaration was already fixed in:
- https://github.com/dragonmantank/cron-expression/pull/175
> Add PHP 8.4 Support

- composer.json
- src/Cron/CronExpression.php
> Remove phpstan/phpstan-webmozart-assert dependency
